version: "3.2"

services:
  python:       
    build: 
      dockerfile: ./Dockerfile
      context: ./
    image: metaflow-docker
    
    # custom environment variables file for parameter configuration
    env_file:
      - .env

    # expose port 8888 so we can connect via a web browser
    ports:
      - "8888:8888"

    # mount current directory as a volume in the container
    volumes:
      - ./:/working
      
    # run shell
    stdin_open: true
    tty: true
    
    # command:
    #   /bin/bash

    # run Jupyter lab
    # command: 
    #   jupyter lab --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token='local_dev'
